interface Http {
    [key: number]: string;
}

const Http: Http = {
    100: 'Continuar',
    101: 'Mudando Protocolos',
    102: 'Processando',
    103: 'Indicações Iniciais',
    200: 'OK',
    201: 'Criado',
    202: 'Aceito',
    203: 'Informações Não Autoritativas',
    204: 'Sem Conteúdo',
    205: 'Conteúdo Restaurado',
    206: 'Conteúdo Parcial',
    207: 'Status Multi-Status',
    208: 'Já Reportado',
    226: 'IM Usado',
    300: 'Múltipla Escolha',
    301: 'Movido Permanentemente',
    302: 'Encontrado',
    303: 'Consulte Outro',
    304: 'Não Modificado',
    305: 'Use Proxy',
    307: 'Redirecionamento Temporário',
    308: 'Redirecionamento Permanente',
    400: 'Pedido Incorreto',
    401: 'Não Autorizado',
    402: 'Pagamento Necessário',
    403: 'Proibido',
    404: 'Não Encontrado',
    405: 'Método Não Permitido',
    406: 'Não Aceitável',
    407: 'Autenticação de Proxy Necessária',
    408: 'Tempo de Pedido Esgotado',
    409: 'Conflito',
    410: 'Desaparecido',
    411: 'Comprimento Necessário',
    412: 'Pré-condição Falhou',
    413: 'Solicitação de Entidade Muito Grande',
    414: 'URI Muito Longo',
    415: 'Tipo de Mídia Não Suportado',
    416: 'Faixa Não Satisfatória',
    417: 'Falha na Expectativa',
    418: 'Sou um bule de chá',
    421: 'Solicitação Direcionada',
    422: 'Entidade Não Processável',
    423: 'Bloqueado',
    424: 'Falha de Dependência',
    425: 'Muito Cedo',
    426: 'Upgrade Necessário',
    428: 'Pré-requisito Necessário',
    429: 'Muitos Pedidos',
    431: 'Campos de Cabeçalho de Solicitação Muito Grandes',
    451: 'Indisponível por Motivos Legais',
    500: 'Erro Interno do Servidor',
    501: 'Não Implementado',
    502: 'Bad Gateway',
    503: 'Serviço Indisponível',
    504: 'Gateway Temporário Indisponível',
    505: 'Versão HTTP Não Suportada',
    506: 'Negocia Também a Variante',
    507: 'Armazenamento Insuficiente',
    508: 'Loop Detectado',
    510: 'Não Estendido',
    511: 'Autenticação de Rede Necessária'
};



export default Http;
